### ISSUE TITLE
Create Deco  has failed to load correctly

### ISSUE THREAD

**Issue by simo-pagliu** [talrey/CreateDeco#10]
If i remove create deco from my modpack, it works just fine, otherwise I get this generic error:

Create Deci (createdeci) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

crash file:
[crash-2022-01-13_20.59.44-fml.txt](https://github.com/talrey/CreateDeco/files/7865623/crash-2022-01-13_20.59.44-fml.txt)
r

**Comment by RedSmileTV** [comment]
I have the same issue in my modpack when I use the mod with the same mods but in a custom profile it works fine but if I have it trying to run from my modpack it also crashes with the same erro
[crash-2022-01-14_15.16.08-fml.txt](https://github.com/talrey/CreateDeco/files/7870943/crash-2022-01-14_15.16.08-fml.txt)
r
