### ISSUE TITLE
[Fabric] Incompatible with Create Sodium Fix fork

### ISSUE THREAD

**Issue by neonishere** [talrey/CreateDeco#103]
I'm using the create fork that fixes the crash for sodium but Deco is not working with it.
It wants me to specifically use the version 0.5.1-d-build.1161+mc1.20.1 of create, but the fork is 0.5.1-d-build.5+mc1.20.1

**Comment by GameBurrow** [comment]
Even the official (non-sodium) currentl release of Create Fabric on Modrinth is build.1161 not build.5 which this mod requires:
https://modrinth.com/mod/create-fabric/versions?g=1.20.1
