### ISSUE TITLE
Windows don't have a  crafting recipe 

### ISSUE THREAD

**Issue by DaPuffer** [talrey/CreateDeco#106]
![image](https://github.com/talrey/CreateDeco/assets/132820752/23699975-bc35-40ec-b96b-811c8aeda9d0)
just this.

**Comment by kenshin33** [comment]
can confirm, On a server  (quiltmc if it has any relevance)

**Comment by CassieRoseZA** [comment]
Can also Confirm on Fabric

**Comment by MonsieurHamter** [comment]
I confirm this issue. Mines are on 1.20.1 createdeco-2.0.0 forge version with create 0.5.1.f.

**Comment by CassieRoseZA** [comment]
So its something to do with how they made the tag and didn't implment it properly? ill see if i can't get a crafttweaker or kubejs script for you guys if u need

**Comment by CassieRoseZA** [comment]
I have a KubeJS Fix 
[CreateDecoFix.js.txt](https://github.com/talrey/CreateDeco/files/13850014/CreateDecoFix.js.txt)
Just remove the .txt

**Comment by MarioSMB** [comment]
The internal tags system makes it harder for mods and modpack developers to support the mod, I would suggest switching to standard tags for things like this.

**Comment by Luviam** [comment]
Same issue here, Forge 1.20.1

**Comment by TheGiga** [comment]
Confirmed in 1.20.1 Forge, Create Deco version `2.0.0-forge-1.20.1`

I've got a [datapack](https://github.com/TheGiga/createdeco-window-crafts) fix for this.  Alternatively, i suggest using [KubeJS fix](https://github.com/talrey/CreateDeco/issues/106#issuecomment-1879700208), that was provided above.

**Comment by drewcassidy** [comment]
Was this resolved with 2.0.1?

**Comment by Luviam** [comment]
> Was this resolved with 2.0.1?

In my case, yes.

**Comment by AstralOrdana** [comment]
yes
