### ISSUE TITLE
Recipe Errors with Worn Brick block variants

### ISSUE THREAD

**Issue by Boxed-catgirl** [talrey/CreateDeco#14]
I noticed this hasn’t been submitted as an issue yet but I have found that the Worn Bricks (specifically) have some problems with their block variants such as the long bricks, tiles, etc . 
For every other brick variant you place the block in the stonecutter or the mechanical saw with the desiree recipe. The Worn brick blocks display their recipes as being a result of smelting the brick item to get all of the variants.

**Comment by TheRealWormbo** [comment]
It seems there are several recipe issues with worn brick (singular, the crafting item) vs worn bricks (the block), such as worn brick being the stone cutter input for a bunch of worn bricks block variations. (This is with CreateDeco 1.2.5)
