### ISSUE TITLE
Create Deco Crash (1.20.1, Fabric)

### ISSUE THREAD

**Issue by Tehemo** [talrey/CreateDeco#143]
Create Deco Crashes because of my Turkish local.

`createdeco:block/palettes/windows/\u0131ron_window_end`

"I" becomes "ı" instead of "i"

Crash log:
https://mclo.gs/R4twbsO

**Comment by McModknower** [comment]
Until the root cause is fixed, you can add `-Duser.country=US -Duser.language=en` to your java arguments as a workaround.
This sets Java's locale to English, preventing the error from arising.

**Comment by AstralOrdana** [comment]
fixed for 2.0.2
