### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by buny690** [talrey/CreateDeco#149]
With Create Deco 2.0.1, My server crashes on startup. Forge 47.2.0 for 1.20.1
Here is the crash report and server log...

[crash-2024-04-16_23.59.02-fml.txt](https://github.com/talrey/CreateDeco/files/15002388/crash-2024-04-16_23.59.02-fml.txt)

[latest.log](https://github.com/talrey/CreateDeco/files/15002391/latest.log)

**Comment by McModknower** [comment]
This is the same crash as #143
