### ISSUE TITLE
No Config and Toggleables [MC1.20.1 / Deco 2.0.2]

### ISSUE THREAD

**Issue by Kalmorph** [talrey/CreateDeco#166]
Hi, I looked around the issues and saw some posts about an "can_press_coins" settings, but when I looked in both my local/server config folders, couldn't find any file for Deco. Ingame also didn't had any sort of config inside the mods or through Create other mods tab.

How can I change this settings? Is it bugged for not being generated?
I'm using Numismatics for currency in my server and wish to disable these coins both crating and from showing in JEI, if possible. Some people may get confused in my server and I'm trying to solve that beforehanded.

**Comment by talrey** [comment]
The config setting was removed a while back. If you want to disable the coins in your pack, I recommend a datapack approach, KubeJS, or a similar recipe-changing mod.
