### ISSUE TITLE
Can't right-click open metal doors

### ISSUE THREAD

**Issue by TeamRustic** [talrey/CreateDeco#18]
Forge 40.1.0
createdeco-1.2.7-1.18.2

Metal doors only open with a redstone signal. (at least the brass one, didn't test the others)

**Comment by talrey** [comment]
there's "locked" and regular variants, are you sure you're not using those? The Locked ones only respond to redstone.

**Comment by ChibiTomo** [comment]
Same here with exactly same versions Forge 40.1.0 & createdeco-1.2.7-1.18.2.

I made sure that this was not the locked versions of the doors. Neither the andesite nor the copper are right clickable.

**Comment by talrey** [comment]
Sorry for how long this has been open. Was updating Fabric and closing issues and fixed this there, I'll check that it's fixed on Forge as well.
