### ISSUE TITLE
[Question] - Fabric Build

### ISSUE THREAD

**Issue by havi05** [talrey/CreateDeco#19]
Sorry for asking here, but I don't use Discord.

Are there any pre-built .jar files for the 1.18 - Fabric Branch?

**Comment by pavog** [comment]
The first official beta build is released on curseforge. [createdeco-fabric-1.2.7-1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/create-deco/files/3795326)

**Comment by havi05** [comment]
Thank you very much!
