### ISSUE TITLE
Crash on starup

### ISSUE THREAD

**Issue by IMaFishEatshark** [talrey/CreateDeco#2]
[crash-2021-10-24_01.58.29-fml.txt](https://github.com/talrey/CreateDeco/files/7403372/crash-2021-10-24_01.58.29-fml.txt)

**Comment by IMaFishEatshark** [comment]
I dont know if this is a createdeco issue or a mod conflict

**Comment by zISKo666** [comment]
Crashing server and client on startup.

Seams to be an issue with Creates latest changes.

**Comment by Jordan231111** [comment]
same issue here crash started happening after updating create

**Comment by cofl** [comment]
Create changed some of the signatures for one of their methods; the linked pull updates Deco to use the new signatures.
