### ISSUE TITLE
All cage lamps have the same texture (1.2.8-1.18.2)

### ISSUE THREAD

**Issue by snoodledev** [talrey/CreateDeco#28]
All variants of the cage lamp have the same red & grey texture in the latest version, both in the inventory and when placed (particles still seem to be correct though).
![createdeco cage lamps bug](https://user-images.githubusercontent.com/71858614/178140396-0164fa0f-f43c-4336-acbb-a0881f61e0e7.png)

**Comment by mbwarn** [comment]
I'm also having this issue since updating to latest version tonight.

**Comment by Atakku** [comment]
![20220726043925](https://user-images.githubusercontent.com/57140941/180911373-a3602cbd-9a42-45dd-8791-b40363a687a5.png)
Same issue here too
