### ISSUE TITLE
[1.18.2 Fabric] Server still fails to launch with the latest version on Fabric 1.18.2

### ISSUE THREAD

**Issue by TofuToons** [talrey/CreateDeco#29]
Version: 1.2.7a-fabric-1.18.2

Server fails to start on launch. 
Crash log:
![image](https://user-images.githubusercontent.com/68460671/178796375-ba7df05d-3125-4ccf-8437-2ac6a25a25e8.png)
Text form:
[server_start_fail.txt](https://github.com/talrey/CreateDeco/files/9104648/server_start_fail.txt)

**Comment by buerrebones** [comment]
We're having this issue as well (same error and everything)

**Comment by amk91** [comment]
I have the same issue as well. Here's the full log

[latest.log](https://github.com/talrey/CreateDeco/files/9106654/latest.log)
.

**Comment by yYRyitYy** [comment]
I am also having the same issue.

**Comment by warior456** [comment]
also createdeco crashing my server

**Comment by yannick1124** [comment]
same here. Is there a manual fix for this? I'm more than happy to edit a file on my server if it can fix this

**Comment by NonRidiculousAdjective** [comment]
also got the error, reported it on discord as well

**Comment by IronPegasus** [comment]
Adding myself to the list. I get this same error when trying to launch with Create Fabric 1.18.2 v0.5.0c.

**Comment by minhtet-htoon** [comment]
I had the exact same issue in single player. Downgrading to Create 0.4.1 Patch 13 fixed the problem. Although not ideal, if you *really* want this mod more than trains and steam engines, it works.

**Comment by warior456** [comment]
with createdeco and extra disabled and create additions updated it works
