### ISSUE TITLE
Catwalks exhibit culling issues with Rubidium or Sodium+Indium

### ISSUE THREAD

**Issue by TheRealWormbo** [talrey/CreateDeco#34]
When using Rubidium to improve rendering performance, catwalk blocks start exhibiting strange culling issues:
![Excessive top face culling of covered catwalk](https://user-images.githubusercontent.com/7620864/184299857-e315b7a4-6b99-4919-97b1-01ef97c08ab3.png)
![Side face of catwalk base not being rendered](https://user-images.githubusercontent.com/7620864/184300089-7aff89bd-78d5-4524-84d7-397b6046c5af.png)

I somewhat assume this is a problem in Rubidium (also see [my report there](https://github.com/Asek3/Rubidium/issues/229)), but I'm opening this issue here as well, in case you have some way of working around it.

**Comment by TheRealWormbo** [comment]
Upon further inspection, the top culling issue also exists in Fabric in combination with Sodium and Indium, but I couldn't replicate the side culling issue there.
Tested combinations:
- Fabric – FabricAPI 0.58.0+1.18.2, Create-mc1.18.2_v0.4.1+637, Create Deco 1.2.7a-fabric-1.18.2, Sodium 1.18.2-0.4.1+build.15, Indium 1.0.7
- Forge – Forge 40.1.68, Create v0.5.0c, Create Deco 1.2.9-1.18.2, Flywheel 0.6.4, Rubidium 0.5.3a

**Comment by CKenJa** [comment]
Happened without Rubidium in Forge's modpack.
It also happens with a lectern instead of a stone.
The handrail must be in contact with the block above.

**Comment by talrey** [comment]
Fixed for next!
