### ISSUE TITLE
Mod Failed To load

### ISSUE THREAD

**Issue by TurboFunder** [talrey/CreateDeco#36]
Create Deco Version: 1.2.9 1.18.2
Create Version: 0.5.0d 1.18.2
Flywheel version: 0.6.5
Forge version: 40.1.68

[crash-2022-08-15_18.13.39-fml.txt](https://github.com/talrey/CreateDeco/files/9344029/crash-2022-08-15_18.13.39-fml.txt)

**Comment by TurboFunder** [comment]
Learned another addon for Create also has this issue
https://github.com/mrh0/createaddition/issues/317#issue-1339684047
Could be the jar file is named differently so the mod doesn't detect it?

**Comment by McSquizzleswag** [comment]
Even I get that, same mod versions but Forge version I was using is 40.1.73

**Comment by Raidobw2** [comment]
Having the same issue!
```
Caused by 1: java.lang.NoClassDefFoundError: com/simibubi/create/repack/registrate/Registrate
		at com.github.talrey.createdeco.CreateDecoMod.<init>(CreateDecoMod.java:53) ~[createdeco-1.2.9-1.18.2.jar%23108!/:1.2.9-1.18.2] 
```
