### ISSUE TITLE
Crash on fabric

### ISSUE THREAD

**Issue by Kuggle01** [talrey/CreateDeco#40]
https://paste.ee/p/8S5o3 I don't know, I have no clue why this would be happening, but it is

**Comment by underscoren** [comment]
I have the same issue, here's a more clean log and crash report:

Minecraft 1.18.2
Fabric 0.14.9
Loaded mods:
Fabric API 0.58.0 
Create Fabric v0.5.0c
Create Deco Fabric 1.2.7a

[latest.log](https://github.com/talrey/CreateDeco/files/9465473/latest.log)
[crash-2022-08-31_23.19.04-client.txt](https://github.com/talrey/CreateDeco/files/9465475/crash-2022-08-31_23.19.04-client.txt)

For anyone stumbling onto this issue, the only way around this crash as of right now is to either not use create deco, or to downgrade create fabric to the previous version (v0.4.1)
