### ISSUE TITLE
Crash with Immersive Weathering

### ISSUE THREAD

**Issue by isaaclepes** [talrey/CreateDeco#42]
Not sure if this would be on Create Deco or Immersive Weathering, so I am opening a ticket with both

Game crashes when Immersive Weathering checks for the block property 'weathering' in createdeco:blue_bricks_stairs

Cannot set property EnumProperty{name=weathering, clazz=class com.ordana.immersive_weathering.common.blocks.Weatherable$WeatheringState, values=[FALSE, TRUE, STABLE]} as it does not exist in Block{createdeco:blue_bricks_stairs}

**Comment by talrey** [comment]
That's definitely an issue on their end, hopefully it got worked out. Feel free to comment on our Discord if it's something they need to work with us on.

**Comment by isaaclepes** [comment]
I never saw any traction on it. I noticed that it only seemed to happen if grass was growing next to one of those blue brick stairs, so I just landscaped the problem away.
