### ISSUE TITLE
The top and bottom coinstack textures appear to be swapped.

### ISSUE THREAD

**Issue by Flyte-less** [talrey/CreateDeco#44]
At least I'm pretty sure they are. Maybe it's intentional but I feel like the shiny side belongs on the top and not the bottom.
![image](https://user-images.githubusercontent.com/83427235/189774496-2e388853-27c8-4d40-b221-b0601179e149.png)
![image](https://user-images.githubusercontent.com/83427235/189774524-822365d8-6de3-4739-8b38-2a47ff421bb9.png)

**Comment by Flyte-less** [comment]
Still present with only Create, Create Deco, and Flywheel loaded
![image](https://user-images.githubusercontent.com/83427235/189775219-c8904f9f-c4c5-4278-9e09-b52dc2c862db.png)
![image](https://user-images.githubusercontent.com/83427235/189775265-f6f84e83-1252-4958-9939-1e3b2c75fd1b.png)
![image](https://user-images.githubusercontent.com/83427235/189775397-a965aa6c-9036-4944-bd6e-ac9d3c133be1.png)

**Comment by talrey** [comment]
Fixed for next release.
