### ISSUE TITLE
Bars cause graphics glitch

### ISSUE THREAD

**Issue by notchriss** [talrey/CreateDeco#45]
MC 1.16.5
Create create-mc1.16.5_v0.3.2g
CreateDeco createdeco-1.1.2-1.16.5

I have a contraption - a gate out of a column of blocks (superglue) on top of Mechanical bearing and Gold Bars (CreateDeco) attached to them using superglue. After turning the contraption only the block directly on top of mechanical bearing stays visible. Others only become visible again if I relog, or leave the area and come back, i.e. chunk reloads presumably. I've tried using different blocks including linear chassis, attaching gates to chassis using slimeball instead of superglue, different combinations of other blocks including vanilla iron bars instead of gold bars, everything works fine everytime, except with CreateDeco bars: gold bars, andesite bars... 

I haven't tested if it's the Mechanical Bearing only or any kind of contraption. 

In one screenshot you can see the gates in process of turning, thats how they are supposed to look like. In another screenshot you can see a single block with superglue on two sides, that's all that's left after the contraption stops.

![2022-09-30_06 11 20](https://user-images.githubusercontent.com/8706925/193184332-f326d0e1-3464-4c6e-933a-4b8af56b1fa7.png)
![2022-09-30_06 11 15](https://user-images.githubusercontent.com/8706925/193184337-8ab5c971-0b32-42fa-b2c2-941ff74e9b59.png)

**Comment by talrey** [comment]
The 1.16.5 version of the mod is pretty much deprecated at this point, but out of curiosity- are you using any other mods that affect how bars and such render?
