### ISSUE TITLE
Missing Forge tags

### ISSUE THREAD

**Issue by xbxbxb123** [talrey/CreateDeco#47]
Several items, for example, all the cast iron items, are missing forge tags that would provide compatibility with other mods. 
For example, adding the Iron and storage block tags to Cast Iron blocks would allow them to be melted down in a Tinkers Constuct smeltery and recycled into an iron block once more.

**Comment by DerCommander323** [comment]
I've noticed the same thing, and checked what exactly was missing:
-Tag `forge:plates` missing from `createdeco:cast_iron_sheet` and `createdeco:zinc_sheet`
-Tag `forge:ingots` missing from `createdeco:cast_iron_ingot`
-Tag `forge:storage_blocks` and `forge:storage_blocks/cast_iron` missing from `createdeco:cast_iron_block`
