### ISSUE TITLE
crash on server only

### ISSUE THREAD

**Issue by Xplodin** [talrey/CreateDeco#49]
https://gist.github.com/Xplodin/36931e6afa6bc6f89f3cd71e38fcd9e4

client loads fine but server does not

**Comment by talrey** [comment]
I released an update a couple days ago, are you still experiencing this crash with 1.2.12?

**Comment by Xplodin** [comment]
ill have to check soon :) thank you for the update!

**Comment by LempekPL** [comment]
Had the same problem even with 1.2.12, but I managed to fix it by adding Flywheel mod to the server
