### ISSUE TITLE
Catwalks display incorrect textures on the bottom faces

### ISSUE THREAD

**Issue by BLOKBUSTR** [talrey/CreateDeco#52]
I stumbled upon this while making a resource pack to fix models for all metal bars when using VanillaTweaks 3D Iron Bars (my pack does work successfully). I am using the latest 1.18.2 Fabric commit of the mod with Create 0.5.0g in a testing installation.

It seems the textures of all Catwalk blocks are incorrectly mirrored across the Z axis on only the underside of the model. All other sides seem correct.

https://user-images.githubusercontent.com/118950712/210124106-4c88868e-236a-4a50-b154-10b60354df74.mp4

**Comment by BLOKBUSTR** [comment]
Through further testing, I found that the model JSON files "catwalk_bottom" and "catwalk_top" can be fixed by mirroring the bottom texture's UV along the X axis (via Blockbench shortcut) back to positive values. This fixes the textures of all catwalk variants.

**Comment by talrey** [comment]
Fixed for next, thanks.
