### ISSUE TITLE
Create Deco metal bars show vanilla texture

### ISSUE THREAD

**Issue by SimKDT** [talrey/CreateDeco#53]
The bars added by the mod have vanilla textures when placed. In 1.18.2, mod added separately to the Better Minecraft Plus modpack

**Comment by talrey** [comment]
oh gods, debugging behavior in a 300 mod pack is several flavors of hell. Luckily for me, **Additional Bars** is on the first page of dependencies. Known issue there, I'm afraid, and fixing the incompatibility isn't really in the cards. Sorry about that.
