### ISSUE TITLE
Zinc Sheet item clashes with Create Addition's Zinc Sheet.

### ISSUE THREAD

**Issue by spectrapulse** [talrey/CreateDeco#62]
https://github.com/mrh0/createaddition/issues/500

**Comment by talrey** [comment]
Should be fixed in the next release.

**Comment by zoeleu** [comment]
@talrey not fixed for fabric

**Comment by talrey** [comment]
The "next release" has not happened yet. I'll take another look at it anyway, just to satisfy my paranoia.
