### ISSUE TITLE
[1.19.2 Fabric] CAN_PRESS_COINS config not working as intended.

### ISSUE THREAD

**Issue by Morphimus** [talrey/CreateDeco#63]
Minecraft 1.19.2
Fabric 0.14.17

Switching the "Can Press Coins" config on should add a recipe that turns a nugget into a coin, right?

![coin_press_screenshot](https://user-images.githubusercontent.com/10824552/230274148-510c5f35-80a9-401a-81ac-1667a8647d16.png)

Instead it seems to just have a recipe with no input.

**Comment by talrey** [comment]
Oh that's very odd. I thought I'd completely turned off the config in 1.19 tbh, the way I was handling it broke in the version update. I'll look into this and see if I can get it working again.

**Comment by talrey** [comment]
Can you confirm if 1.3.1 fixed this or if it's still happening?

**Comment by Morphimus** [comment]
The recipe is functioning! Recipe does indeed now display properly, and it also works in the actual presser, I checked.

![coin_press_screenshot2](https://user-images.githubusercontent.com/10824552/234397478-63c571f9-fe9e-464c-84f7-fca46120e251.png)

Setting the config true or false did not seem to effect this however.

**Comment by talrey** [comment]
Yeah the config not working is known, the way I'd been disabling the recipe doesn't seem to work in 1.19 and to be honest I was considering just removing the option entirely. CraftTweaker or another recipe / datapack editing mod can cover that well enough though, if you need to remove/change it for a modpack.
