### ISSUE TITLE
Decals seem to determine where they will be placed incorrectly 

### ISSUE THREAD

**Issue by ephys** [talrey/CreateDeco#65]
In the image below, if I right click the decal on the wall, nothing will happen.

![image](https://user-images.githubusercontent.com/1280915/232062847-9970f072-0db9-4842-8462-612af9922b80.png)

That's because it's actually trying to place it on another block, even though that's not the one I'm interacting with. Here is where it would be placed if I had a block behind it

![image](https://user-images.githubusercontent.com/1280915/232063398-427b0e26-5082-49e4-9d49-9ff38ce53e20.png)

It seems that the block is trying to determine what its orientation is going to be based on where the player is looking at (like signs when placed on the floor), instead of which side of the block was clicked (like signs when placed on walls)

Version: 1.3.0-1.18.2

**Comment by talrey** [comment]
A good idea. I've changed them to do this in 1.3.1.

**Comment by ephys** [comment]
Thanks!
