### ISSUE TITLE
CreateDeco trapdoors do not stay attached when glued to trains

### ISSUE THREAD

**Issue by PhilipSykes** [talrey/CreateDeco#67]
When you add a CreateDeco trap door of any type to a train and glue it.
![2023-04-20_22 12 14](https://user-images.githubusercontent.com/85830485/233489050-a463714d-ce50-4c39-9ea4-e252bf42bb1f.png)

The trapdoor is not added to the train when you assemble it 
![2023-04-20_22 12 57](https://user-images.githubusercontent.com/85830485/233489142-64185277-cb9b-4265-8237-68f0d3c51946.png)

The Trapdoor and glue around it remains in place
![2023-04-20_22 13 05](https://user-images.githubusercontent.com/85830485/233489268-590876fb-5079-4c4c-878d-3017db17c911.png)

**Comment by PINPAL** [comment]
How did you manage to fix this?
