### ISSUE TITLE
Trapdoors cannot be crafted.

### ISSUE THREAD

**Issue by Svenstihl2** [talrey/CreateDeco#68]
Hey I can't craft the trapdoors: Andesite Trapdoor, Zinc Trapdoor, it's the same recipe as the bars. Think there are with all trapdoors from the mod.
![Screenshot_35](https://user-images.githubusercontent.com/65452274/233773828-8d20b2dc-1820-43c4-8670-7f8728e668a8.png)
Fabric: 1.19.2 
Createdeco 1.2.13-1.19.2

Greetings Sven

**Comment by enkryptor** [comment]
A similar problem, albeit I can't craft the bars:

expected:
![image](https://user-images.githubusercontent.com/668156/233862114-9ab9b439-a658-4d74-a75d-a69ea5cc3f45.png)

actual:
![image](https://user-images.githubusercontent.com/668156/233862147-3faa338f-9246-4355-8b16-d9b6cb008333.png)

**Comment by talrey** [comment]
This is with version 1.3.0, right? Try the update I released today, it should be fixed.

**Comment by enkryptor** [comment]
Fixed in 1.3.1
