### ISSUE TITLE
Metal trapdoors are considered unmovable & Locked Doors are openable

### ISSUE THREAD

**Issue by BLOKBUSTR** [talrey/CreateDeco#72]
I discovered this in v1.3.0-1.19.2 Fabric. Firstly, all five trapdoor variants in this mod cannot be moved by kinetics, and will not be assembled on trains. I tried changing the Create gameplay config to see if enabling movement for obsidian and others would fix this, but it apparently did not.

![2023-04-28_21 17 37](https://user-images.githubusercontent.com/118950712/235283376-46400eeb-a55b-46b4-a124-5c25645e3322.png)

I tested most other blocks in this mod just in case, and it seems this first issue applies only to the trapdoors. While testing this though, I accidentally discovered that all the locked doors do not behave as they're intended... They can be opened and closed normally like a regular door, and even in Survival. They still function properly with redstone though.

**Comment by BLOKBUSTR** [comment]
Shoot, I realized a bit late that half of this issue is a duplicate of #67, my bad...

**Comment by talrey** [comment]
Did 1.3.1 fix these issues for you?

**Comment by BLOKBUSTR** [comment]
The trapdoor issue has indeed been resolved in 1.3.1, though they can't be interacted with on trains and other contraptions. The locked doors are still able to be interacted with the same as regular doors.

https://user-images.githubusercontent.com/118950712/235391654-b953b950-2467-424e-b9e1-9aa014955d88.mp4

**Comment by talrey** [comment]
Yet another Material thing. Mojang pls. Fixed.
