### ISSUE TITLE
Catwalks over conveyors do not block player movement

### ISSUE THREAD

**Issue by robertblutz** [talrey/CreateDeco#73]
If a catwalk is placed directly over a conveyor belt and a player stands on the catwalk, they will still be moved by the conveyor.  
I thought this might be useful a way to cover up floor-level conveyors being used to transfer rotation instead of carrying items, but the motion of the conveyor does not seem to be affected by the catwalk.

**Comment by talrey** [comment]
See, I thought so too when I first worked on them, hence why they can do that at all. Unfortunately I've yet to find a way of actually blocking that motion. Catwalks will get a rework at some point, maybe I'll find a way then.
