### ISSUE TITLE
Game breaking when placing decal on the ground

### ISSUE THREAD

**Issue by Matik1665** [talrey/CreateDeco#74]
When trying to put decals on the ground (allowed only on the sides of the block), my game crashes with this error:

![image](https://user-images.githubusercontent.com/84602176/236384029-b1484454-c194-4cd4-b811-318017024d3b.png)

I tried twice and it gave me the same result, so it's not a one-time error.

**Comment by talrey** [comment]
Make sure you're using Create Deco 1.3.2, which should fix that crash.
