### ISSUE TITLE
Cast Iron and Netherite Ladders not showing recipes

### ISSUE THREAD

**Issue by Avchong** [talrey/CreateDeco#76]
I use REI for the recipes but the Cast Iron and Netherite ladders are not showing or work on the stonecutter: 

![Captura de pantalla 2023-05-07 a la(s) 21 37 57](https://user-images.githubusercontent.com/37880577/236728456-a213ce46-b088-4a2d-8b2e-30a9af2fa92d.png)
![Captura de pantalla 2023-05-07 a la(s) 21 36 26](https://user-images.githubusercontent.com/37880577/236728459-f12a6149-86d6-425f-acf0-474154a645e4.png)

Version: createdeco-1.3.2-1.19.2

**Comment by talrey** [comment]
Can you post the console log? I'd like to see what error specifically it's having there, thanks.

**Comment by Avchong** [comment]
[latest.log](https://github.com/talrey/CreateDeco/files/11446604/latest.log)

Here you go, this is the latest log I got

**Comment by talrey** [comment]
Sorry for the delay. There's a lot of errors in there, but nothing about Deco or REI. I'm thoroughly confused tbh. I'll check on it while I'm updating to 0.5.1 today.

**Comment by brotazoa** [comment]
If I may add my thoughts. Create Deco doesn't actually add the "c:plates/cast_iron", or "c:plates/netherite" tags, but references those tags as the input ingredients for the respective recipes. I was able to fix this issue on my server by making a datapack to populate these two tags. Your mileage may vary.

**Comment by GamerTable** [comment]
I'm having the same issue on the latest version still
https://pastebin.com/aDsqNvtP
