### ISSUE TITLE
Catwalks placed on upper side of block disappear

### ISSUE THREAD

**Issue by akochi** [talrey/CreateDeco#77]
Hi,

When placing any kind of catwalks on the upper side of a block, it immediatly disappears visually while still being there physically (blocks movement). It only reappers after quitiing and reloading.

Placing new ones through extension (create's "fat arrow") works fine.
Placing a catwalk on top of a block works fine.

Minecraft 1.19.2
Forge 43.2.0
Java 17.0.4
Windows 11 22H2

Mods installed:
Create 0.5.0.i
Create Deco 1.3.2-1.19.2

https://github.com/talrey/CreateDeco/assets/46505416/b704a3ca-ed15-4b9b-8267-69ece27e2549

**Comment by DoktorKto420** [comment]
The catwalk will also reappear when you place a block above it (where the handrail hitbox is), unless it's only me.
