### ISSUE TITLE
[1.18.1] Crashes with the current version of Create and Flywheel

### ISSUE THREAD

**Issue by ArchieBeepBoop** [talrey/CreateDeco#8]
Flywheel and Create have been updated as of 3 hours ago to fix quite a few rendering issues.

Notably, create deco seems to be calling a function that is now different and that causes a crash.

Crashlog:
https://pastebin.com/EgKTXRPU

**Comment by UdoMorgenstern** [comment]
current version is in this case:
flywheel-forge-1.18-0.5.1.jar
create-mc1.18.1_v0.4c.jar

should be i assume:
create_version=1.18.1_v0.4c+64
flywheel_version=1.18-0.5.1.44

**Comment by mobiusdt** [comment]
Looks like lines 858-860 need to be updated to have a supplier:
```
        .onRegister(CreateRegistrate.connectedTextures(
          new SheetMetalCTBehaviour(SpriteShifts.SHEET_METAL_SIDES.get(metal))
        ))
```
I think all that needs to be changed is this:
```
        .onRegister(CreateRegistrate.connectedTextures(() ->
          new SheetMetalCTBehaviour(SpriteShifts.SHEET_METAL_SIDES.get(metal))
        ))
```
There are probably other issues that would show up after this has been updated though.
