### ISSUE TITLE
Create Deco Not Compatible with Create .5.1.a Update

### ISSUE THREAD

**Issue by ClaudiusMinimus** [talrey/CreateDeco#80]
createdeco-1.3.2-1.19.2.jar is not compatible with the new Create .5.1.a update.
![image](https://github.com/talrey/CreateDeco/assets/17887664/4893e2a3-b695-4c49-97e8-aa99d2e05cab)

**Comment by talrey** [comment]
The update was released yesterday, friend. The Create dev team mentioned in their announcement that there was a lot of changes to the code and to give add-ons some time to update since it'll take a while. I'm working on it.

**Comment by ClaudiusMinimus** [comment]
> The update was released yesterday, friend. The Create dev team mentioned in their announcement that there was a lot of changes to the code and to give add-ons some time to update since it'll take a while. I'm working on it.

As a modpack developer, I fully understand the pressure others can place on developers. This issue report is not intended to place pressure on you, but simply to notify you in case you had not seen the update - after all, Minecraft is not real life. 

The other reason is to take pressure off of me. I placed links to this and other mods we are waiting on. My players too get impatient and this was a way to keep them at bay.
![image](https://github.com/talrey/CreateDeco/assets/17887664/cc47ecb1-8c30-49af-9a34-7c40ebfa0dbd)
Maybe other players will see this notice and be patient with you as well. 
Thank you for making a wonderful mod and contributing to the Create Minecraft community!
Best Regards,
CM
