### ISSUE TITLE
extending the train hull collision boxes

### ISSUE THREAD

**Issue by tehbeard** [talrey/CreateDeco#81]
It would be nice if the collision box could be extended or tweaked to cover the sides as well as the centre.

Currently it allows you to clip into it when walking next to, 

![image](https://github.com/talrey/CreateDeco/assets/734177/22941d42-f4ca-4d4b-a54d-a7c1a9d40320)

or fall through where it looks to be solid above.

![image](https://github.com/talrey/CreateDeco/assets/734177/d5beac74-56d4-48e9-8177-798db00061e8)

![image](https://github.com/talrey/CreateDeco/assets/734177/8de6e3fd-5e0c-41f3-8271-a92e7a71b711)

**Comment by talrey** [comment]
Minecraft isn't really designed to do this, fences are basically the only block with a bigger hitbox than one cube. You might notice that even Create's crushing wheels only have a cube hitbox in the middle.

I do wish I could, though.
