### ISSUE TITLE
Bars Z-Fight with solid blocks

### ISSUE THREAD

**Issue by LandofHeros2234** [talrey/CreateDeco#83]
The bars Z-Fight with solid blocks. They do not Z-Fight with each other
![2023-06-05_08 28 41](https://github.com/talrey/CreateDeco/assets/126440322/9d20e8da-6a00-4888-968f-e69c707fdf4b)

**Comment by RenegadeT1tan** [comment]
A quick fix is to use a resource pack to solve the problem at the vanilla iron bars json level. I am using [z-fighting metal bars fix](https://www.curseforge.com/minecraft/texture-packs/z-fighting-metal-bars-fix) and it fixes Create Deco even though it doesn't include files for it. The [Vanilla Tweaks](https://vanillatweaks.net/picker/resource-packs/) Iron Bars Fix (which you can find under the 1.19 'Fixes' category) should also work and is included with the first pack and I believe it is what works the magic that affects CreateDeco.

**Comment by Adome11** [comment]
> and it fixes Create Deco even though it doesn't include files for it.

Pretty sure this mod just reuses the iron bars block model while just changing its texture, hence why it fixes it. Also explains why the issue exists in the first place.
